### ISSUE TITLE
Shizuku and root install not working

### ISSUE THREAD

**Issue by Turhvjbufv** [ImranR98/Obtainium#1200]
**Describe the bug**

Root install just doesn't work, just says error with the name of the app
Shizuku install crashes the app
**To Reproduce**
Enable shizuku install, allow obtaininum to use shizuku and try to install an app, obtaininum crashes
....
Enable root, try to install an app, just shows an error with the app name in it, no logs(if you want I can give you?)

Logs are only from shizuku download using sui application
**Screenshots and Logs**

Comments
**Please complete the following information:**
 - Device: A72
 - OS: lineage 20
 - Obtainium Version: 0.14.41
 -Android 13

**Comment by Turhvjbufv** [comment]
Bug, idk why but it doesn't show steps or logs so it's here in comments
Logs
FATAL EXCEPTION: main
Process: dev.imranr.obtainium, PID: 16935
java.lang.NoSuchMethodError: No interface method getPackageInstaller()Landroid/content/pm/IPackageInstaller; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
	at n2.d.a(Unknown Source:8)
	at dev.imranr.obtainium.MainActivity.b0(Unknown Source:6)
	at dev.imranr.obtainium.MainActivity.V(Unknown Source:64)
	at dev.imranr.obtainium.MainActivity.R(Unknown Source:0)
	at m2.c.onMethodCall(Unknown Source:2)
	at i3.j$a.a(Unknown Source:17)
	at v2.c.l(Unknown Source:18)
	at v2.c.m(Unknown Source:40)
	at v2.c.i(Unknown Source:0)
	at v2.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by SebiTalent04** [comment]
Can reproduce with Shizuku.

Device: Pixel 6a
OS: GrapeheneOS 14 (UQ1A.231205.015)
Obtainium version: 0.14.41

**Comment by abUwUser** [comment]
Can reproduce with video

Device: Samsung Galaxy M23
OS: One UI 5.1 (TP1A.220624.014.M236BXXS5CWK7)
Obtanium version: 0.14.41

https://github.com/ImranR98/Obtainium/assets/27961224/ee193f86-1deb-4e8c-8c8f-0838715c48f2

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.4-beta

**Comment by Turhvjbufv** [comment]
Currently I can't check, so I'm closing it as completed if it's not completed, open a new issue/write a comment here and I'll reopen this issue

**Comment by brian6932** [comment]
Fixed for me

**Comment by Pogogo007** [comment]
Root installer still errors out for me on KernelSU

**Comment by Turhvjbufv** [comment]
Opening since root installer doesn't seem to work for me neither
Shizuku(sui) does seem to work

**Comment by soredake** [comment]
Same problem, root/shizuku install are broken.

**Comment by ImranR98** [comment]
A lot of comments here mention Shizuku, which (if I understand correctly) is not what the original issue was about (root). Shizuku does seem to work for some people, but I haven't seen anyone saying the root method works for them, so it might be removed later. Both these methods were contributed by @re7gog in #1184 and #1230 (I haven't used Shizuku and don't plan on rooting any device) so I may not be able to troubleshoot this.

**Comment by re7gog** [comment]
Well, I'll replace root with Sui later, because it looks like root is unreliable
