### ISSUE TITLE
"Add App" page sometimes doesn't re-render

### ISSUE THREAD

**Issue by gepbird** [ImranR98/Obtainium#1530]
**Prerequisites**

I have checked the other issues and haven't found a duplicate.

**Describe the bug**

Toggling switches on the Add App page won't cause re-renders, the switch doesn't toggle visually on tapping (under certain conditions, see below).

**To Reproduce**
1. Start Obtainium (if the app was running before, close it first)
2. Tap on Add App
3. Input "https://github.com/ImranR98/Obtainium" to the source URL textbox
4. Change Override Source to GitHub
5. Tap on "Include prereleases" switch
6. Observe that the switch did not toggle visually

**Screenshots and Logs**

https://github.com/ImranR98/Obtainium/assets/29818440/9ecfeeff-d2ba-4fb9-9a75-a6ef666f4e7c

**Please complete the following information:**
 - Device: Samsung Galaxy A12
 - OS: Android 12
 - Obtainium Version: 1.1.2

**Additional context**

After changing the Override Source to GitHub, not only "Include prereleases" option is bugged, but every other option except the last: "Try inferring App ID from source". When the last option is toggled, a re-render occures and all the previously toggled switches update.
More importantly, after changing the Override Source to anything (eg. GitLab) then back to GitHub, this issue does't happen and all switches work until the user navigates away from the Add App page then back.

**Comment by gepbird** [comment]
<details><summary>Stack trace</summary>

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Not in inclusive range 0..19: 20

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _GeneratedFormState.someValueChanged (package:obtainium/components/generated_form.dart:250:23)
#2      _GeneratedFormState.build.<anonymous closure>.<anonymous closure> (package:obtainium/components/generated_form.dart:381:33)
#3      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
#4      _GeneratedFormState.build.<anonymous closure> (package:obtainium/components/generated_form.dart:379:31)
#5      _MaterialSwitchState._handleChanged (package:flutter/src/material/switch.dart:847:23)
#6      ToggleableStateMixin._handleTap (package:flutter/src/material/toggleable.dart:234:19)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#19     _invoke1 (dart:ui/hooks.dart:328:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#1e49b
════════════════════════════════════════════════════════════════════════════════════════════════════
```
