### ISSUE TITLE
Crash after coming back from enabling apk installs

### ISSUE THREAD

**Issue by WIPocket** [ImranR98/Obtainium#1536]
**Prerequisites**

**Describe the bug**

It crashed.

**To Reproduce**
Install Obtainium, add an app from GitHub that isnt installed yet. Click install, allow apk installations. After enabling, come back from the settings.

**Screenshots and Logs**
Crash log:
```
type: crash
osVersion: google/panther/panther:14/AP1A.240405.002/2024040900:user/release-keys
package: dev.imranr.obtainium.fdroid:22583
process: dev.imranr.obtainium.fdroid
processUptime: 208 + 488 ms
installer: org.fdroid.basic

java.lang.RuntimeException: Unable to resume activity {dev.imranr.obtainium.fdroid/dev.imranr.obtainium.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=0, data=null} to activity {dev.imranr.obtainium.fdroid/dev.imranr.obtainium.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5202)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5235)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:254)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:91)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2551)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=0, data=null} to activity {dev.imranr.obtainium.fdroid/dev.imranr.obtainium.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5767)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5189)
	... 16 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
	at v0.q.onActivityResult(Unknown Source:146)
	at io.flutter.embedding.engine.c$c.c(Unknown Source:25)
	at io.flutter.embedding.engine.c.onActivityResult(Unknown Source:14)
	at io.flutter.embedding.android.d.p(Unknown Source:51)
	at io.flutter.embedding.android.c.onActivityResult(Unknown Source:10)
	at android.app.Activity.dispatchActivityResult(Activity.java:9170)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5760)
	... 17 more
```

**Please complete the following information:**
 - Device: Pixel 7
 - OS: GrapheneOS
 - Obtainium Version: 1.1.1 (F-Droid)

**Additional context**

**Comment by ImranR98** [comment]
Hmm, I haven't been able to replicate this, neither on an Android emulator nor on a GrapheneOS P8P. Does it happen every time?

**Comment by WIPocket** [comment]
Yes, it seems to be consistent. [Here is exactly what I did.](https://wipocket.eu/tmp/2y/Ly7GyZ2Kw9041KDPVHRAzFb7e9vFFFdZ2IISAXamdBCvp7K4bd-obtainium.mp4) It does not seem to be specific to a single Github repo, I first ran into it with a different app than here.
