### ISSUE TITLE
I can't import my JSON File anymore...

### ISSUE THREAD

**Issue by IbrahimHabibii** [ImranR98/Obtainium#1689]
Hello,

i tried to import my JSON File but it don't work anymore...I really don't know why but since yesterday it was like that. I tried on different Phones too but it don't work.

It says: invalid input but not the Reason why. So I tried to import it in "Read You" App to try see if it works vor whats the Problem is and it don't work there too. It says this and I hope it helps by fixing the Problem:

Version: 0.10.1
Device: Xiaomi M2007J20CG
System: Android 14 (API 34)

Stack trace: 

be.ceau.opml.OpmlParseException: org.xmlpull.v1.XmlPullParserException: Unexpected <! (position:START_DOCUMENT null@1:1 in java.io.InputStreamReader@48ac9b7) 
	at me.ash.reader.infrastructure.rss.OPMLDataSource.parseFileInputStream(OPMLDataSource.kt:550)
	at me.ash.reader.domain.service.OpmlService$saveToDatabase$2.invokeSuspend(OpmlService.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@48f1f90, Dispatchers.Default]
Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected <! (position:START_DOCUMENT null@1:1 in java.io.InputStreamReader@48ac9b7) 
	at com.android.org.kxml2.io.KXmlParser.peekType(KXmlParser.java:1040)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at be.ceau.opml.OpmlParser.extract(OpmlParser.java:49)
	at me.ash.reader.infrastructure.rss.OPMLDataSource.parseFileInputStream(OPMLDataSource.kt:20)
	... 6 more

I really hope you can help me, because I use the Apps daily, so it is important for me to be able to use  them again. Thanks!

**Comment by IbrahimHabibii** [comment]
I found the Mistake haha! It was because I downloaded the JSON File with the wrong Browser! Happy that it works now!

**Comment by ACR-Jeff** [comment]
> I found the Mistake haha! It was because I downloaded the JSON File with the wrong Browser! Happy that it works now!

What does this mean with the `Wrong Browser`? 
I am having the same issue on GrapheneOS, Importing just doesn't do anything, I downloaded both Obtainium and Obtainium-Emulation-Pack using both Vanadium Browser and Fennec Browser, Obtainium seems to install fine, But importing doesn't show anything in the list after importing the json.
