### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by LoHub** [ImranR98/Obtainium#1764]
**Describe the bug**

I would like to report a carsh log. I do not know how to reproduce.

```
type: crash
package: de.seemoo.at_tracking_detection.release:45
process: de.seemoo.at_tracking_detection.release
processUptime: 194 + 216 ms
installer: dev.imranr.obtainium

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.seemoo.at_tracking_detection.release/de.seemoo.at_tracking_detection.ui.MainActivity}: android.view.InflateException: Binary XML file line #30 in de.seemoo.at_tracking_detection.release:layout/activity_main: Binary XML file line #30 in de.seemoo.at_tracking_detection.release:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.view.InflateException: Binary XML file line #30 in de.seemoo.at_tracking_detection.release:layout/activity_main: Binary XML file line #30 in de.seemoo.at_tracking_detection.release:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #30 in de.seemoo.at_tracking_detection.release:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.RuntimeException: Exception inflating de.seemoo.at_tracking_detection.release:navigation/main_navigation line 172
	at K1.I.b(Unknown Source:133)
	at B.b.a(Unknown Source:1789)
	at T4.l.getValue(Unknown Source:20)
	at androidx.navigation.fragment.NavHostFragment.g(Unknown Source:2)
	at androidx.navigation.fragment.NavHostFragment.onCreate(Unknown Source:0)
	at androidx.fragment.app.F.performCreate(Unknown Source:21)
	at androidx.fragment.app.m0.e(Unknown Source:50)
	at androidx.fragment.app.m0.k(Unknown Source:179)
	at androidx.fragment.app.e0.z(Unknown Source:1628)
	at androidx.fragment.app.e0.R(Unknown Source:91)
	at androidx.fragment.app.e0.y(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:54)
	at androidx.fragment.app.S.onCreateView(SourceFile:3)
	at androidx.fragment.app.K.dispatchFragmentsOnCreateView(Unknown Source:8)
	at androidx.fragment.app.K.onCreateView(SourceFile:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:957)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:885)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1011)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at k.y.h(Unknown Source:23)
	at k.j.setContentView(SourceFile:2)
	at de.seemoo.at_tracking_detection.ui.MainActivity.onCreate(Unknown Source:967)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: de.seemoo.at_tracking_detection.database.models.device.DeviceType
	at a.a.J(Unknown Source:273)
	at K1.I.c(Unknown Source:48)
	at K1.I.a(Unknown Source:96)
	at K1.I.a(Unknown Source:592)
	at K1.I.b(Unknown Source:40)
	... 44 more
Caused by: java.lang.ClassNotFoundException: de.seemoo.at_tracking_detection.database.models.device.DeviceType
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at java.lang.Class.forName(Class.java:512)
	at a.a.J(Unknown Source:206)
	... 48 more
Caused by: java.lang.ClassNotFoundException: de.seemoo.at_tracking_detection.database.models.device.DeviceType
	... 52 more
```

**Please complete the following information:**
 - Device: Pixel 8
 - OS: GrapheneOS
 - Obtainium Version: v1.1.15

**Comment by ImranR98** [comment]
Not qn Obtainium bug. The crash log says it's from `de.seemoo.at_tracking_detection` (Airguard app). Obtainium is only mentioned in the logs because you installed it through Obtainium.
