### ISSUE TITLE
Obtainium crash.  Other possible issues.

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1891]
Pixel 7, GrapheneOS
Obtainium 1.1.26

Lots of squirrely behavior recently.

Pulling down from the top to update everything, the progress meter gets about half way (202 apps total in my profile - I have github and gitlab tokens), then it stops and waits for some time, finally reporting:

```
Not Found [Book Reader and Ministocks]

Could not find a suitable release [Cheogram]

Connection timed out [Wire, Bromite, Skiff Mail, RedReader, Geometric Weather, RadioDroid, Mastodon, iNaturalist, microMathematics Plus, Skiff Calendar, neutriNote CE, OpenDocument Reader, Sky Map, I2P, Mixin, Record You, Material Files, Aard 2, Fair Email, Telegram, Organic Maps, JRPN 16C, jtx Board, and Orbot]
```

A bunch then come up in the apps list with a download icon (phone icon with the down arrow).  After some time most correct themselves (it appears the Installed version number/name is different from the latest and the app corrects for this difference.  Two remain saying they need an update:

```
Cwtch
1.15.0 installed
1.15.1 latest
Tapping update, it reports "apps updated", but the version does not change and the download icon is still present
Last Update Check: <date> ... https://git.openprivacy.ca/cwtch.im/cwch-ui/releases/download/v1.15.1/cwtch-v1.15.1.apk

Stocks Widget
3.9.830 Installed
3.9.934 Latest
Tapping update, I get:
Some Errors Occurred
Conflict [Stocks Widget]
   Last Update Check: <date> app-purefoss-debug.apk
```

These are the ones that correct themselves after some time:

```
Addy.io:
v5.3.2 Installed
5.3.2 Latest
updated itself?  Now says 5.3.2 Installed/Latest

Hash-checker
3.7.2-thirdparty Installed
3.7.2 Latest
updated itself?  Now says 3.7.2 Installed/Latest

Open Camera
1.53.1 Installed
1_53_1 Latest
Updated itself?  Now says 1_53_1 Installed/Latest

Open Note Scanner
1.0.34-fdroid Installed
1.0.35 latest
I was able to update.  Now 1.0.35 Installed/Latest

OpenDocument Reader
3.24-pro Installed
3.31 Latest
Updated itself?  Now says 3.31 Installed/Latest

Orbot
17.3.2-RC-1-tor-0.4.8.12 Installed
17.3.2-RC-1 Latest
Updated itself?  Now says 17.3.2-RC-1 Installed/Latest

Organic Maps
2024.09.08-7-Web Installed
2024.09.08-7 Latest
Updated itself?  Now says 2.24.09.08-7 Installed/Latest

Sky Map
1.10.1 - RC2 Installed
1.10.1-RC2 Latest
Updated itself?  Now says 1.10.1-RC2 Installed/Latest

Tor Browser
115.2.1-release (13.5.6) Installed
13.5.6 Latest
Updated itself?  Now says 13.5.6 Installed

Trail Sense
6.3.0-dev Installed
6.3.0 Latest
Updated itself?  Now says 6.3.0 Installed/Latest
```

Then, after some more time, I get a popup, "Obtainium keeps stopping".  

Tapping "Show details", I get:

```
type: crash
osVersion: google/panther/panther:14/AP2A.240905.003/2024092900:user/release-keys
package: dev.imranr.obtainium:22833
process: dev.imranr.obtainium
processUptime: 5141 + 354 ms
installer: dev.imranr.obtainium

u4.r: lateinit property callResult has not been initialized
	at s1.d$a.a(Unknown Source:7)
	at s1.d$a.c(Unknown Source:5)
	at s1.e.onNewIntent(Unknown Source:80)
	at io.flutter.embedding.engine.c$c.c(Unknown Source:18)
	at io.flutter.embedding.engine.c.onNewIntent(Unknown Source:14)
	at io.flutter.embedding.android.e.x(Unknown Source:20)
	at io.flutter.embedding.android.d.onNewIntent(Unknown Source:13)
	at android.app.Activity.performNewIntent(Activity.java:9031)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1635)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1692)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4228)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4236)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:58)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by DiagonalArg** [comment]
In case the crash was caused by the 3 apps that are giving me trouble, I'll give a couple of details here:

Cheogram
https://git.sr.ht/~singpolyma/cheogram-android
The version I have installed is 2.15.3-4, which is the latest

Cwtch.im
On that page is the link, 
https://git.openprivacy.ca/cwtch.im/cwtch-ui/releases/download/v1.15.1/cwtch-v1.15.1.apk
I have 1.15.0 installed, but after update, which completes without complaint, I've still got 1.15.0

Stocks Widget
https://github.com/premnirmal/StockTicker/releases
On update I get:
   Some Errors Occurred
   Conflict [Stocks Widget]

**Comment by ImranR98** [comment]
Seems like there are a bunch of separate issues here.

For Cheogram, there may be something wrong with your config. Try the one from here: https://apps.obtainium.imranr.dev/?categories=messaging

For stocks widget, the APK you downloaded has a different signature from the one in the currently installed version. So it's not an Obtainium issue - Android wouldn't allow you to install the APK anyways. You can confirm by manually downloading and trying to install it. You should check with the developer that the change in signature is expected and if so, uninstall/reinstall the app.

For Cwtch, I confirmed on my end that the APK at that link is actually version 1.15.0 - seems like they attached the wrong APK to the link.

The real bugs are:
1. Apps that get into an incorrect state and "fix themselves" later
    - Will look into this.
2. The crash
    - Looks like it is coming from some underlying dependency (Flutter or one of the Flutter packages I use). It may not be fixable from Obtainium code but that needs to be confirmed.

**Comment by DiagonalArg** [comment]
Old.  Not relevant any more.  We can close this.
